on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  cut-release:
    name: Cut Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@main
        with:
          configuration: 'release-changelog-builder-config.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          draft: false
          prerelease: false

  release-artifacts:
    name: Release Artifacts
    strategy:
      matrix:
        toolchain:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_name: vault-env-exec-linux-amd64
          - os: macos-12
            target: aarch64-apple-darwin
            asset_name: vault-env-exec-darwin-arm64
    runs-on: ${{ matrix.toolchain.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Artifact
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload release binary
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/vault-env-exec
          asset_name: ${{ matrix.toolchain.asset_name }}
          tag: ${{ github.ref }}
